<a href="https://colab.research.google.com/github/shikhakewat2002/basic-operation-on-matrices/blob/main/matrixhehe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A= np.array([[1,2,3],
            [2,3,4],
            [4,5,6]])
B=np.array([[2,4,3],
           [3,3,3],
           [4,3,5]])
print("Matrix of A is :\n",A,"\n")
print("Matrix of B is :\n",B,"\n")
addition= A+B
print("\naddition of A and B:\n", addition)
subtraction=A-B
print("\nsubtraction of A and B:\n", subtraction)
matrix_multiplication= A@B
print("\nmatrix multiplication of A and B:\n",matrix_multiplication)
element_wise_multiplication= A*B
print("\nelement-wise multiplication of A and B:\n",element_wise_multiplication)
print("\n scaler multiplication of A:\n", 2*A)

Matrix of A is :
 [[1 2 3]
 [2 3 4]
 [4 5 6]] 

Matrix of B is :
 [[2 4 3]
 [3 3 3]
 [4 3 5]] 


addition of A and B:
 [[ 3  6  6]
 [ 5  6  7]
 [ 8  8 11]]

subtraction of A and B:
 [[-1 -2  0]
 [-1  0  1]
 [ 0  2  1]]

matrix multiplication of A and B:
 [[20 19 24]
 [29 29 35]
 [47 49 57]]

element-wise multiplication of A and B:
 [[ 2  8  9]
 [ 6  9 12]
 [16 15 30]]

 scaler multiplication of A:
 [[ 2  4  6]
 [ 4  6  8]
 [ 8 10 12]]


In [7]:
rows = int(input("Enter the number of rows: "))
columns = int(input("Enter the number of columns: "))

print("\nEnter elements of matrix S:")
S= np.array([[int(input(f"A[{i+1},{j+1}]:")) for j in range(columns)] for i in range(rows)])

print("\nEnter elements of matrix K:")
K= np.array([[int(input(f"B[{i+1},{j+1}]:")) for j in range(columns)] for i in range(rows)])

print("\nMatrix S is :\n",S,"\n")
print("Matrix K is :\n",K,"\n")

print("\naddition of S and K:\n", S+K)
print("\nsubtraction of S and K:\n", S-K)
print("\nElement-wise multiplication:\n",S*K)


row_num =  int(input("\nEnter row number to display of Matrix S: "))-1
col_num = int(input("Enter column number to display of Matrix K: "))-1
print(f"\nRow {row_num+1} of Matrix S is: {S[row_num]}")
print(f"column {col_num+1} of Matrix K is: \n{K[:,col_num]}")


Enter the number of rows: 3
Enter the number of columns: 3

Enter elements of matrix S:
A[1,1]:2
A[1,2]:5
A[1,3]:4
A[2,1]:6
A[2,2]:5
A[2,3]:4
A[3,1]:3
A[3,2]:4
A[3,3]:6

Enter elements of matrix K:
B[1,1]:4
B[1,2]:3
B[1,3]:5
B[2,1]:4
B[2,2]:3
B[2,3]:2
B[3,1]:4
B[3,2]:5
B[3,3]:4

Matrix S is :
 [[2 5 4]
 [6 5 4]
 [3 4 6]] 

Matrix K is :
 [[4 3 5]
 [4 3 2]
 [4 5 4]] 


addition of S and K:
 [[ 6  8  9]
 [10  8  6]
 [ 7  9 10]]

subtraction of S and K:
 [[-2  2 -1]
 [ 2  2  2]
 [-1 -1  2]]

Element-wise multiplication:
 [[ 8 15 20]
 [24 15  8]
 [12 20 24]]

Enter row number to display of Matrix S: 3
Enter column number to display of Matrix K: 2

Row 3 of Matrix S is: [3 4 6]
column 2 of Matrix K is: 
[3 3 5]
